name: Sharedhosting deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.6'

    - name: Install Composer Dependencies
      run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest

    - name: Test Database Connection
      run: |
        echo "Testing MySQL Connection..."
        mysql --host=$DB_HOST --port=$DB_PORT --user=$DB_USERNAME --password=$DB_PASSWORD -e "SHOW DATABASES"
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Run Laravel Commands
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        php artisan migrate --force
        php artisan config:cache
        php artisan config:clear

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Assets
      run: npm ci && npm run prod

    - name: Deploy to Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DESTINATION }}
