name: Sharedhosting deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.6'
    
    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest
  
    - name: Run Laravel commands
      #env:
        #FTP_HOST: ${{ secrets.FTP_HOST }}
        #FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        #FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        #FTP_DESTINATION: ${{ secrets.FTP_DESTINATION }}
        #DB_CONNECTION: mysql
        #DB_HOST: ${{ secrets.DB_HOST }}
        #DB_PORT: ${{ secrets.DB_PORT }}
        #DB_DATABASE: ${{ secrets.DB_DATABASE }}
        #DB_USERNAME: ${{ secrets.DB_USERNAME }}
        #DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        
        php artisan migrate --force
        php artisan db:seed --force
        npm install
        npm run prod
    
    - name: Deploy to hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DESTINATION }}
